name: DeadBeSpectators
version: 1.0
main: com.github.nishitox.deadbespectators.DeadBeSpectators
api-version: 1.15

commands:
  deadBeSpectators:
    usage: "§cusage: /deadbespectators [enable|disable|config]"
    permission: op