name: DeadSpectators
version: ${project.version}
main: com.github.nishitox.deadspectators.DeadSpectators
api-version: 1.15

commands:
  deadBeSpectators:
    usage: "§cusage: /deadspectators [enable|disable|config]"
    permission: op